name: Feature Branch Build

on:
  push:
    branches:
      - feature/**

jobs:
  feature-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: jfrog-release
          server-username: ${{ secrets.JFROG_USERNAME }}
          server-password: ${{ secrets.JFROG_PASSWORD }}
          overwrite-settings: true

      - name: Build
        run: mvn clean install

      - name: Deploy Maven Artifact to JFrog
        run: mvn deploy
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}

      - name: Login to JFrog Docker Registry
        run: echo ${{ secrets.JFROG_PASSWORD }} | docker login trialvs67i0.jfrog.io -u ${{ secrets.JFROG_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t trialvs67i0.jfrog.io/todo-docker/todo-app:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push trialvs67i0.jfrog.io/todo-docker/todo-app:${{ github.sha }}
